
version: "3.7"

services:
  profiling-service:
    build: ./profiling
    ports:
      - "7080:7080"

  membership-service:
    build: ./membership
    ports:
      - "8080:8080"

  user-service:
    build: ./user
    ports:
      - "9080:9080"

